from airtrack.settings import AIRTRACK_LOG_LEVEL
from airtrack.settings import AIRTRACK_SESSION_PATH
from airtrack.settings import AIRTRACK_SESSIONS_LOG_FILE
from airtrack.settings import AIRTRACK_SESSION_NAME
from airtrack.settings import AIRTRACK_BPOD_SERIAL_PORT
from airtrack.settings import AIRTRACK_STREAM_SESSION_TO_STDOUT

PYBPOD_API_LOG_LEVEL = AIRTRACK_LOG_LEVEL
PYBPOD_API_LOG_FILE = AIRTRACK_SESSIONS_LOG_FILE
# stream the session file to the stdin (terminal)
PYBPOD_API_STREAM2STDOUT = AIRTRACK_STREAM_SESSION_TO_STDOUT
# accept commands from the stdin
PYBPOD_API_ACCEPT_STDIN = False
PYBPOD_SESSION_PATH = AIRTRACK_SESSION_PATH
PYBPOD_SESSION = AIRTRACK_SESSION_NAME
PYBPOD_SERIAL_PORT = AIRTRACK_BPOD_SERIAL_PORT
# SUPPORTED BPOD FIRMWARE VERSION
# TARGET_BPOD_FIRMWARE_VERSION = "9"  # 0.7.5
# TARGET_BPOD_FIRMWARE_VERSION = "13" # 0.7.9
# TARGET_BPOD_FIRMWARE_VERSION = "15" # 0.8
# TARGET_BPOD_FIRMWARE_VERSION = "17" # 0.9
TARGET_BPOD_FIRMWARE_VERSION = "22"
EMULATOR_BPOD_MACHINE_TYPE = 3
BPOD_BNC_PORTS_ENABLED = [True, True]
BPOD_WIRED_PORTS_ENABLED = [True, True]
BPOD_BEHAVIOR_PORTS_ENABLED = [True, True, True, True, True, True, True, True]
PYBPOD_NET_PORT = None
PYBPOD_BAUDRATE = 1312500
PYBPOD_SYNC_CHANNEL = 255
PYBPOD_SYNC_MODE = 1
